// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// Equipment is an object representing the database table.
type Equipment struct {
	ID   int64  `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name string `boil:"name" json:"name" toml:"name" yaml:"name"`

	R *equipmentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L equipmentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var EquipmentColumns = struct {
	ID   string
	Name string
}{
	ID:   "id",
	Name: "name",
}

var EquipmentTableColumns = struct {
	ID   string
	Name string
}{
	ID:   "equipments.id",
	Name: "equipments.name",
}

// Generated where

var EquipmentWhere = struct {
	ID   whereHelperint64
	Name whereHelperstring
}{
	ID:   whereHelperint64{field: "\"equipments\".\"id\""},
	Name: whereHelperstring{field: "\"equipments\".\"name\""},
}

// EquipmentRels is where relationship names are stored.
var EquipmentRels = struct {
}{}

// equipmentR is where relationships are stored.
type equipmentR struct {
}

// NewStruct creates a new relationship struct
func (*equipmentR) NewStruct() *equipmentR {
	return &equipmentR{}
}

// equipmentL is where Load methods for each relationship are stored.
type equipmentL struct{}

var (
	equipmentAllColumns            = []string{"id", "name"}
	equipmentColumnsWithoutDefault = []string{"name"}
	equipmentColumnsWithDefault    = []string{"id"}
	equipmentPrimaryKeyColumns     = []string{"id"}
	equipmentGeneratedColumns      = []string{"id"}
)

type (
	// EquipmentSlice is an alias for a slice of pointers to Equipment.
	// This should almost always be used instead of []Equipment.
	EquipmentSlice []*Equipment
	// EquipmentHook is the signature for custom Equipment hook methods
	EquipmentHook func(context.Context, boil.ContextExecutor, *Equipment) error

	equipmentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	equipmentType                 = reflect.TypeOf(&Equipment{})
	equipmentMapping              = queries.MakeStructMapping(equipmentType)
	equipmentPrimaryKeyMapping, _ = queries.BindMapping(equipmentType, equipmentMapping, equipmentPrimaryKeyColumns)
	equipmentInsertCacheMut       sync.RWMutex
	equipmentInsertCache          = make(map[string]insertCache)
	equipmentUpdateCacheMut       sync.RWMutex
	equipmentUpdateCache          = make(map[string]updateCache)
	equipmentUpsertCacheMut       sync.RWMutex
	equipmentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var equipmentAfterSelectMu sync.Mutex
var equipmentAfterSelectHooks []EquipmentHook

var equipmentBeforeInsertMu sync.Mutex
var equipmentBeforeInsertHooks []EquipmentHook
var equipmentAfterInsertMu sync.Mutex
var equipmentAfterInsertHooks []EquipmentHook

var equipmentBeforeUpdateMu sync.Mutex
var equipmentBeforeUpdateHooks []EquipmentHook
var equipmentAfterUpdateMu sync.Mutex
var equipmentAfterUpdateHooks []EquipmentHook

var equipmentBeforeDeleteMu sync.Mutex
var equipmentBeforeDeleteHooks []EquipmentHook
var equipmentAfterDeleteMu sync.Mutex
var equipmentAfterDeleteHooks []EquipmentHook

var equipmentBeforeUpsertMu sync.Mutex
var equipmentBeforeUpsertHooks []EquipmentHook
var equipmentAfterUpsertMu sync.Mutex
var equipmentAfterUpsertHooks []EquipmentHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *Equipment) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *Equipment) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *Equipment) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *Equipment) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *Equipment) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *Equipment) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *Equipment) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *Equipment) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *Equipment) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range equipmentAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddEquipmentHook registers your hook function for all future operations.
func AddEquipmentHook(hookPoint boil.HookPoint, equipmentHook EquipmentHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		equipmentAfterSelectMu.Lock()
		equipmentAfterSelectHooks = append(equipmentAfterSelectHooks, equipmentHook)
		equipmentAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		equipmentBeforeInsertMu.Lock()
		equipmentBeforeInsertHooks = append(equipmentBeforeInsertHooks, equipmentHook)
		equipmentBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		equipmentAfterInsertMu.Lock()
		equipmentAfterInsertHooks = append(equipmentAfterInsertHooks, equipmentHook)
		equipmentAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		equipmentBeforeUpdateMu.Lock()
		equipmentBeforeUpdateHooks = append(equipmentBeforeUpdateHooks, equipmentHook)
		equipmentBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		equipmentAfterUpdateMu.Lock()
		equipmentAfterUpdateHooks = append(equipmentAfterUpdateHooks, equipmentHook)
		equipmentAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		equipmentBeforeDeleteMu.Lock()
		equipmentBeforeDeleteHooks = append(equipmentBeforeDeleteHooks, equipmentHook)
		equipmentBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		equipmentAfterDeleteMu.Lock()
		equipmentAfterDeleteHooks = append(equipmentAfterDeleteHooks, equipmentHook)
		equipmentAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		equipmentBeforeUpsertMu.Lock()
		equipmentBeforeUpsertHooks = append(equipmentBeforeUpsertHooks, equipmentHook)
		equipmentBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		equipmentAfterUpsertMu.Lock()
		equipmentAfterUpsertHooks = append(equipmentAfterUpsertHooks, equipmentHook)
		equipmentAfterUpsertMu.Unlock()
	}
}

// One returns a single equipment record from the query.
func (q equipmentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Equipment, error) {
	o := &Equipment{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: failed to execute a one query for equipments")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all Equipment records from the query.
func (q equipmentQuery) All(ctx context.Context, exec boil.ContextExecutor) (EquipmentSlice, error) {
	var o []*Equipment

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "model: failed to assign all query results to Equipment slice")
	}

	if len(equipmentAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all Equipment records in the query.
func (q equipmentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to count equipments rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q equipmentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "model: failed to check if equipments exists")
	}

	return count > 0, nil
}

// Equipments retrieves all the records using an executor.
func Equipments(mods ...qm.QueryMod) equipmentQuery {
	mods = append(mods, qm.From("\"equipments\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"equipments\".*"})
	}

	return equipmentQuery{q}
}

// FindEquipment retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindEquipment(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Equipment, error) {
	equipmentObj := &Equipment{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"equipments\" where \"id\"=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, equipmentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "model: unable to select from equipments")
	}

	if err = equipmentObj.doAfterSelectHooks(ctx, exec); err != nil {
		return equipmentObj, err
	}

	return equipmentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Equipment) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("model: no equipments provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(equipmentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	equipmentInsertCacheMut.RLock()
	cache, cached := equipmentInsertCache[key]
	equipmentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			equipmentAllColumns,
			equipmentColumnsWithDefault,
			equipmentColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, equipmentGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(equipmentType, equipmentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(equipmentType, equipmentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"equipments\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"equipments\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "model: unable to insert into equipments")
	}

	if !cached {
		equipmentInsertCacheMut.Lock()
		equipmentInsertCache[key] = cache
		equipmentInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the Equipment.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Equipment) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	equipmentUpdateCacheMut.RLock()
	cache, cached := equipmentUpdateCache[key]
	equipmentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			equipmentAllColumns,
			equipmentPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, equipmentGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("model: unable to update equipments, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"equipments\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 0, wl),
			strmangle.WhereClause("\"", "\"", 0, equipmentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(equipmentType, equipmentMapping, append(wl, equipmentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update equipments row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by update for equipments")
	}

	if !cached {
		equipmentUpdateCacheMut.Lock()
		equipmentUpdateCache[key] = cache
		equipmentUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q equipmentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all for equipments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected for equipments")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o EquipmentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("model: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), equipmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"equipments\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, equipmentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to update all in equipment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to retrieve rows affected all in update all equipment")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Equipment) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("model: no equipments provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(equipmentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	equipmentUpsertCacheMut.RLock()
	cache, cached := equipmentUpsertCache[key]
	equipmentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			equipmentAllColumns,
			equipmentColumnsWithDefault,
			equipmentColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			equipmentAllColumns,
			equipmentPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("model: unable to upsert equipments, could not build update column list")
		}

		ret := strmangle.SetComplement(equipmentAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(equipmentPrimaryKeyColumns))
			copy(conflict, equipmentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQuerySQLite(dialect, "\"equipments\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(equipmentType, equipmentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(equipmentType, equipmentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "model: unable to upsert equipments")
	}

	if !cached {
		equipmentUpsertCacheMut.Lock()
		equipmentUpsertCache[key] = cache
		equipmentUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single Equipment record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Equipment) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("model: no Equipment provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), equipmentPrimaryKeyMapping)
	sql := "DELETE FROM \"equipments\" WHERE \"id\"=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete from equipments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by delete for equipments")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q equipmentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("model: no equipmentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from equipments")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for equipments")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o EquipmentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(equipmentBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), equipmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"equipments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, equipmentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "model: unable to delete all from equipment slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "model: failed to get rows affected by deleteall for equipments")
	}

	if len(equipmentAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Equipment) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindEquipment(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *EquipmentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := EquipmentSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), equipmentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"equipments\".* FROM \"equipments\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, equipmentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "model: unable to reload all in EquipmentSlice")
	}

	*o = slice

	return nil
}

// EquipmentExists checks if the Equipment row exists.
func EquipmentExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"equipments\" where \"id\"=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "model: unable to check if equipments exists")
	}

	return exists, nil
}

// Exists checks if the Equipment row exists.
func (o *Equipment) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return EquipmentExists(ctx, exec, o.ID)
}
