// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

var TableNames = struct {
	User           string
	UserCharacters string
	UserEquipments string
	UserQuests     string
}{
	User:           "user",
	UserCharacters: "user_characters",
	UserEquipments: "user_equipments",
	UserQuests:     "user_quests",
}
